version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: horta_postgres
    restart: always
    environment:
      POSTGRES_USER: horta
      POSTGRES_PASSWORD: horta1234
      POSTGRES_DB: horta_db
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
