"""campos_resiliencia_horta

Revision ID: 87fb30218f89
Revises: f04957d936ae
Create Date: 2026-05-22 10:39:10.315628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87fb30218f89'
down_revision: Union[str, Sequence[str], None] = 'f04957d936ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Hortas', sa.Column('tem_cisterna', sa.Boolean(), nullable=True))
    op.add_column('Hortas', sa.Column('fonte_agua', sa.String(length=50), nullable=True))
    op.add_column('Hortas', sa.Column('tipo_solo', sa.String(length=50), nullable=True))
    op.add_column('Hortas', sa.Column('area_permeavel', sa.Float(), nullable=True))
    op.add_column('Hortas', sa.Column('nivel_vulnerabilidade', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Hortas', 'nivel_vulnerabilidade')
    op.drop_column('Hortas', 'area_permeavel')
    op.drop_column('Hortas', 'tipo_solo')
    op.drop_column('Hortas', 'fonte_agua')
    op.drop_column('Hortas', 'tem_cisterna')
    # ### end Alembic commands ###
