"""fotos do forum: tabela Post_Imagens, drop imagem_path

Revision ID: fa212378d876
Revises: f6a7b8c9d0e1
Create Date: 2026-06-23 13:16:28.369625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa212378d876'
down_revision: Union[str, Sequence[str], None] = 'f6a7b8c9d0e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Post_Imagens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('object_key', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=40), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['Posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('object_key')
    )
    op.create_index(op.f('ix_Post_Imagens_post_id'), 'Post_Imagens', ['post_id'], unique=False)
    op.drop_column('Posts', 'imagem_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Posts', sa.Column('imagem_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_Post_Imagens_post_id'), table_name='Post_Imagens')
    op.drop_table('Post_Imagens')
    # ### end Alembic commands ###
